// packages/effects/common-ui/src/ui/fallback/fallback.vue
<script setup lang="ts">
import type { FallbackProps } from './fallback';

import { computed, defineAsyncComponent } from 'vue';
import { useRouter } from 'vue-router';

import { ArrowLeft, RotateCw } from '@nova/icons';
import { $t } from '@nova/locales';

import { VbenButton } from '@nova-core/shadcn-ui';

interface Props extends FallbackProps {}

defineOptions({
  name: 'Fallback',
});

const props = withDefaults(defineProps<Props>(), {
  description: '',
  homePath: '/',
  image: '',
  showBack: true,
  status: 'coming-soon',
  title: '',
});

const Icon403 = defineAsyncComponent(() => import('./icons/icon-403.vue'));
const Icon404 = defineAsyncComponent(() => import('./icons/icon-404.vue'));
const Icon500 = defineAsyncComponent(() => import('./icons/icon-500.vue'));
const IconHello = defineAsyncComponent(
  () => import('./icons/icon-coming-soon.vue'),
);
const IconOffline = defineAsyncComponent(
  () => import('./icons/icon-offline.vue'),
);

const titleText = computed(() => {
  if (props.title) {
    return props.title;
  }

  switch (props.status) {
    case '403': {
      return $t('ui.fallback.forbidden');
    }
    case '404': {
      return $t('ui.fallback.pageNotFound');
    }
    case '500': {
      return $t('ui.fallback.internalError');
    }
    case 'coming-soon': {
      return $t('ui.fallback.comingSoon');
    }
    case 'offline': {
      return $t('ui.fallback.offlineError');
    }
    default: {
      return '';
    }
  }
});

const descText = computed(() => {
  if (props.description) {
    return props.description;
  }
  switch (props.status) {
    case '403': {
      return $t('ui.fallback.forbiddenDesc');
    }
    case '404': {
      return $t('ui.fallback.pageNotFoundDesc');
    }
    case '500': {
      return $t('ui.fallback.internalErrorDesc');
    }
    case 'offline': {
      return $t('ui.fallback.offlineErrorDesc');
    }
    default: {
      return '';
    }
  }
});

const fallbackIcon = computed(() => {
  switch (props.status) {
    case '403': {
      return Icon403;
    }
    case '404': {
      return Icon404;
    }
    case '500': {
      return Icon500;
    }
    case 'coming-soon': {
      return IconHello;
    }
    case 'offline': {
      return IconOffline;
    }
    default: {
      return null;
    }
  }
});

const showBack = computed(() => {
  return props.status === '403' || props.status === '404';
});

const showRefresh = computed(() => {
  return props.status === '500' || props.status === 'offline';
});

const { push } = useRouter();

// 返回首页
function back() {
  push(props.homePath);
}

function refresh() {
  location.reload();
}
</script>

<template>
  <div class="flex size-full flex-col items-center justify-center duration-300">
    <img v-if="image" :src="image" class="md:1/3 w-1/2 lg:w-1/4" />
    <component
      :is="fallbackIcon"
      v-else-if="fallbackIcon"
      class="md:1/3 h-1/3 w-1/2 lg:w-1/4"
    />
    <div class="flex-col-center">
      <slot v-if="$slots.title" name="title"></slot>
      <p
        v-else-if="titleText"
        class="text-foreground mt-8 text-2xl md:text-3xl lg:text-4xl"
      >
        {{ titleText }}
      </p>
      <slot v-if="$slots.describe" name="describe"></slot>
      <p
        v-else-if="descText"
        class="text-muted-foreground md:text-md my-4 lg:text-lg"
      >
        {{ descText }}
      </p>
      <slot v-if="$slots.action" name="action"></slot>
      <VbenButton v-else-if="showBack" size="lg" @click="back">
        <ArrowLeft class="mr-2 size-4" />
        {{ $t('common.backToHome') }}
      </VbenButton>
      <VbenButton v-else-if="showRefresh" size="lg" @click="refresh">
        <RotateCw class="mr-2 size-4" />
        {{ $t('common.refresh') }}
      </VbenButton>
    </div>
  </div>
</template>

// src/components/ui/fallback/fallback.tsx
import { ArrowLeftOutlined, ReloadOutlined } from '@ant-design/icons';
import { Button } from 'antd';
import { useMemo } from 'react';
import { useNavigate } from 'react-router';
import Icon403 from './icons/icon-403';
import Icon404 from './icons/icon-404';
import Icon500 from './icons/icon-500';
import IconComingSoon from './icons/icon-coming-soon';
import IconOffline from './icons/icon-offline';

export interface FallbackProps {
  /**
   * 描述
   */
  description?: string;
  /**
   * 首页路由地址
   * @default /
   */
  homePath?: string;
  /**
   * 默认显示的图片
   */
  image?: string;
  /**
   * 内置类型
   */
  status?: '403' | '404' | '500' | 'coming-soon' | 'offline';
  /**
   * 页面提示语
   */
  title?: string;
  /**
   * 自定义操作按钮
   */
  action?: React.ReactNode;
}

export function Fallback(props: FallbackProps) {
  const { description, homePath = '/', image, status = 'coming-soon', title, action } = props;

  const navigate = useNavigate();

  const titleText = useMemo(() => {
    if (title) {
      return title;
    }
    switch (status) {
      case '403':
        return '403 禁止访问';
      case '404':
        return '404 页面未找到';
      case '500':
        return '500 服务器错误';
      case 'coming-soon':
        return '即将推出';
      case 'offline':
        return '网络连接中断';
      default:
        return '';
    }
  }, [status, title]);

  const descText = useMemo(() => {
    if (description) {
      return description;
    }
    switch (status) {
      case '403':
        return '您没有权限访问该页面';
      case '404':
        return '抱歉，您访问的页面不存在';
      case '500':
        return '抱歉，服务器发生错误';
      case 'offline':
        return '请检查您的网络连接';
      default:
        return '';
    }
  }, [status, description]);

  const FallbackIcon = useMemo(() => {
    switch (status) {
      case '403':
        return Icon403;
      case '404':
        return Icon404;
      case '500':
        return Icon500;
      case 'coming-soon':
        return IconComingSoon;
      case 'offline':
        return IconOffline;
      default:
        return null;
    }
  }, [status]);

  const showBack = status === '403' || status === '404';
  const showRefresh = status === '500' || status === 'offline';

  const back = () => {
    navigate(homePath);
  };

  const refresh = () => {
    window.location.reload();
  };

  return (
    <div className="flex size-full flex-col items-center justify-center duration-300">
      {image ? (
        <img src={image} className="md:1/3 w-1/2 lg:w-1/4" alt="fallback" />
      ) : (
        FallbackIcon && <FallbackIcon />
      )}
      <div className="flex flex-col items-center justify-center">
        <p className="text-foreground mt-8 text-2xl md:text-3xl lg:text-4xl">{titleText}</p>
        <p className="text-muted-foreground md:text-md my-4 lg:text-lg">{descText}</p>
        {action || (
          <>
            {showBack && (
              <Button type="primary" size="large" onClick={back} icon={<ArrowLeftOutlined />}>
                返回首页
              </Button>
            )}
            {showRefresh && (
              <Button type="primary" size="large" onClick={refresh} icon={<ReloadOutlined />}>
                刷新页面
              </Button>
            )}
          </>
        )}
      </div>
    </div>
  );
}
